groupName: acme.webhook.duckdns.org

logLevel: 2

replicaCount: 1

duckdns:
  token: ""

secret:
  existingSecret: false
  existingSecretName: ""

clusterIssuer:
  email: cert-manager-webhook-duckdns@cluster.home.arpa
  staging:
    create: false
  production:
    create: false

image:
  repository: ghcr.io/chadgeary/cert-manager-webhook-duckdns
  tag: 1.0.0
  pullPolicy: IfNotPresent

certManager:
  serviceAccountName: cert-manager

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# Pod Security Context
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  runAsNonRoot: true
  runAsUser: 11000
  seccompProfile:
    type: RuntimeDefault

# Container Security Context to be set on workload
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

nodeSelector: {}

tolerations: []

affinity: {}
